"""BenefitIQ canonical field registry — IRDAI F15 aligned (full DD, 268 F15 fields).

Canonical names = BenefitIQ DB column names (ORM-aligned).
F15 field names are synonyms so TPA files using F15 headers map automatically.
Additional F15 fields without DB columns are OPTIONAL (informational, not stored).
Tables: claims (175), member_master (55), policy_master (40)
All mandatory=False for pilot — no upload blocking, only DQ scoring.
"""
from enum import Enum


class Tier(str, Enum):
    CRITICAL = "critical"
    IMPORTANT = "important"
    OPTIONAL = "optional"


def _f(name, tier, dtype, mandatory=False, synonyms=None, f15=None):
    return {
        "canonical": name, "tier": tier, "dtype": dtype,
        "mandatory": mandatory, "synonyms": synonyms or [], "f15_ref": f15,
    }


REGISTRY = {
    # ---- CLAIMS (175 fields: 20 DB-schema + 155 F15-only) ----
    "claims": [
        # -- DB-schema fields (canonical = ORM column name) --
        _f('tpa_code', Tier.CRITICAL, 'int', synonyms=['txt_tpa_code', 'tpa name'], f15='A,B,C'),
        _f('insurer_code', Tier.CRITICAL, 'int', synonyms=['txt_insurer_code', 'insurer name'], f15='A,B,C'),
        _f('master_policy_number', Tier.CRITICAL, 'str', synonyms=['txt_master_policy_number'], f15='A'),
        _f('policy_number', Tier.CRITICAL, 'str', synonyms=['txt_policy_number'], f15='A,B,C'),
        _f('member_reference_key', Tier.IMPORTANT, 'str', synonyms=['txt_member_reference_key', 'member id', 'mrk', 'member ref'], f15='B,C'),
        _f('sum_insured', Tier.CRITICAL, 'float', synonyms=['num_sum_insured'], f15='B,C'),
        _f('claim_number', Tier.CRITICAL, 'str', synonyms=['txt_claim_number', 'claim id', 'claim no', 'claimno'], f15='C'),
        _f('diagnosis_code_l1', Tier.IMPORTANT, 'str', synonyms=['txt_diagnosis_code_ level _i', 'diagnosis_code__level__i', 'icd', 'ailment', 'diagnosis code', 'icd code'], f15='C'),
        _f('hospital_name', Tier.IMPORTANT, 'str', synonyms=['txt_name_of_the_hospital', 'name_of_the_hospital', 'hospital', 'hospital name'], f15='C'),
        _f('date_of_admission', Tier.CRITICAL, 'date', synonyms=['admission date', 'adm date'], f15='C'),
        _f('date_of_discharge', Tier.IMPORTANT, 'date', synonyms=['discharge date', 'dis date'], f15='C'),
        _f('total_amount_claimed', Tier.IMPORTANT, 'float', synonyms=['num_total_amount_claimed'], f15='C'),
        _f('total_claim_paid', Tier.CRITICAL, 'float', synonyms=['num_total_claim_paid', 'paid amount', 'paid', 'amount paid'], f15='C'),
        _f('provider_code', Tier.OPTIONAL, 'str', synonyms=['txt_hospital_code', 'hospital_code', 'provider', 'provider id', 'network hospital', 'txt_provider_code'], f15='C'),
        _f('claim_type', Tier.OPTIONAL, 'int', synonyms=['txt_type_of_claim_payment', 'type_of_claim_payment', 'type of claim', 'cashless reimbursement'], f15='C'),
        _f('hospital_is_network', Tier.OPTIONAL, 'bool', synonyms=['boo_hospital_is_network_provider', 'hospital_is_network_provider'], f15='C'),
        _f('copay_percentage', Tier.OPTIONAL, 'float', synonyms=['num_percentage_of_copayment', 'percentage_of_copayment'], f15='C'),
        _f('claim_status', Tier.CRITICAL, 'code', synonyms=['txt_claim_status', 'claim status', 'status'], f15='C'),
        _f('outstanding_amount', Tier.OPTIONAL, 'float', synonyms=['num_outstanding_amount', 'outstanding', 'outstanding amount', 'amount outstanding'], f15=None),
        _f('incurred_amount', Tier.OPTIONAL, 'float', synonyms=['num_incurred_amount', 'incurred', 'incurred amount', 'incurred claim amount'], f15=None),
        # -- F15-only fields (informational; not stored in current DB schema) --
        _f('uw_office_code', Tier.OPTIONAL, 'str', synonyms=['txt_uw_office_code'], f15='A'),
        _f('no_of_members_insured', Tier.OPTIONAL, 'int', synonyms=['no.of members insured'], f15='A'),
        _f('employee_id', Tier.OPTIONAL, 'str', synonyms=[], f15='B,C'),
        _f('date_of_birth', Tier.OPTIONAL, 'date', synonyms=[], f15='B,C'),
        _f('age_of_insured', Tier.OPTIONAL, 'int', synonyms=['num_age_of_insured'], f15='B,C'),
        _f('date_policy_start', Tier.OPTIONAL, 'date', synonyms=[], f15='A,B,C'),
        _f('date_policy_end', Tier.OPTIONAL, 'date', synonyms=[], f15='A,B,C'),
        _f('product_type', Tier.OPTIONAL, 'int', synonyms=['txt_product_type'], f15='A,B,C'),
        _f('type_of_policy', Tier.OPTIONAL, 'int', synonyms=['txt_type_of_policy'], f15='A,B,C'),
        _f('distribution_channel_code', Tier.OPTIONAL, 'int', synonyms=['txt_distribution_channel_code'], f15='A'),
        _f('type_of_premium', Tier.OPTIONAL, 'bool', synonyms=['boo_type_of_premium'], f15='A'),
        _f('previous_policy_number', Tier.OPTIONAL, 'str', synonyms=['txt_previous_policy_number'], f15='A,B'),
        _f('floater_applicable', Tier.OPTIONAL, 'bool', synonyms=['boo_floater_applicable'], f15='B,C'),
        _f('gender', Tier.OPTIONAL, 'int', synonyms=['txt_gender'], f15='B,C'),
        _f('child_claim_number', Tier.OPTIONAL, 'str', synonyms=['txt_child_claim_number'], f15='C'),
        _f('procedure_code__level_i', Tier.OPTIONAL, 'str', synonyms=['txt_procedure_code_ level_i'], f15='C'),
        _f('registration_number_of_hospital', Tier.OPTIONAL, 'str', synonyms=['txt_registration_number_of_hospital'], f15='C'),
        _f('pan_of_hospital', Tier.OPTIONAL, 'str', synonyms=['txt_pan_of_hospital'], f15='C'),
        _f('pin_code_of_hospital', Tier.OPTIONAL, 'int', synonyms=['txt_pin_code_of_hospital'], f15='C'),
        _f('room_charges_claimed', Tier.OPTIONAL, 'float', synonyms=['num_room_charges_claimed'], f15='C'),
        _f('nursing__charges_claimed', Tier.OPTIONAL, 'float', synonyms=['num_nursing_ charges_claimed'], f15='C'),
        _f('surgery_charges_claimed', Tier.OPTIONAL, 'float', synonyms=['num_surgery_charges_claimed'], f15='C'),
        _f('consultation_charges_claimed', Tier.OPTIONAL, 'float', synonyms=['num_consultation_charges_claimed'], f15='C'),
        _f('diagonostic_charges_claimed', Tier.OPTIONAL, 'float', synonyms=['num_diagonostic_charges_claimed'], f15='C'),
        _f('medicine_charges_claimed', Tier.OPTIONAL, 'float', synonyms=['num_medicine_charges_claimed'], f15='C'),
        _f('miscellaneous__charges_claimed', Tier.OPTIONAL, 'float', synonyms=['num_miscellaneous_ charges_claimed'], f15='C'),
        _f('pre_hospitalisation_expenses_claimed', Tier.OPTIONAL, 'float', synonyms=['num_pre_hospitalisation_expenses_claimed'], f15='C'),
        _f('post_hospitalisation_expenses_claimed', Tier.OPTIONAL, 'float', synonyms=['num_post_hospitalisation_expenses_claimed'], f15='C'),
        _f('professional_charges__claimed', Tier.OPTIONAL, 'float', synonyms=['num_professional_charges _claimed'], f15='C'),
        _f('ot_charges_claimed', Tier.OPTIONAL, 'float', synonyms=['num_ot_charges_claimed'], f15='C'),
        _f('surgical_implant_charges_claimed', Tier.OPTIONAL, 'float', synonyms=['num_surgical_implant charges_claimed'], f15='C'),
        _f('indemnity_paid', Tier.OPTIONAL, 'float', synonyms=['num_indemnity_paid'], f15='C'),
        _f('hospital_daily_cash_benefit_paid', Tier.OPTIONAL, 'float', synonyms=['num_hospital_daily_cash_benefit_paid'], f15='C'),
        _f('critical_illness_benefit_paid', Tier.OPTIONAL, 'float', synonyms=['num_critical_illness_benefit_paid'], f15='C'),
        _f('surgical_cash_benefit_paid', Tier.OPTIONAL, 'float', synonyms=['num_surgical_cash_benefit_paid'], f15='C'),
        _f('convalescence_benefit_paid', Tier.OPTIONAL, 'float', synonyms=['num_convalescence_benefit_paid'], f15='C'),
        _f('reason_for_rejection_of_claim', Tier.OPTIONAL, 'str', synonyms=['txt_reason_for_rejection_of_claim'], f15='C'),
        _f('claim_remarks', Tier.OPTIONAL, 'str', synonyms=['txt_claim_remarks'], f15='C'),
        _f('diagnosis_code__level__ii', Tier.OPTIONAL, 'str', synonyms=['txt_diagnosis_code_ level_ ii'], f15='C'),
        _f('diagnosis_code__level__iii', Tier.OPTIONAL, 'str', synonyms=['txt_diagnosis_code_ level_ iii'], f15='C'),
        _f('procedure_code__level_ii', Tier.OPTIONAL, 'str', synonyms=['txt_procedure_code_ level_ii'], f15='C'),
        _f('procedure_code__level_iii', Tier.OPTIONAL, 'str', synonyms=['txt_procedure  code_ level_iii'], f15='C'),
        _f('medical_history__level_i', Tier.OPTIONAL, 'str', synonyms=['txt_medical_history_ level_i'], f15='C'),
        _f('procedure_description_level_i', Tier.OPTIONAL, 'str', synonyms=['txt_procedure_description_level_i'], f15='C'),
        _f('procedure_description_level_ii', Tier.OPTIONAL, 'str', synonyms=['txt_procedure_description_level_ii'], f15='C'),
        _f('procedure_description_level_iii', Tier.OPTIONAL, 'str', synonyms=['txt_procedure_description_level_iii'], f15='C'),
        _f('medical_history__level_ii', Tier.OPTIONAL, 'str', synonyms=['txt_medical_history_ level_ii'], f15='C'),
        _f('medical_history__level_iii', Tier.OPTIONAL, 'str', synonyms=['txt_medical_history_ level_iii'], f15='C'),
        _f('system_of_medicine_used', Tier.OPTIONAL, 'int', synonyms=['txt_system_of_medicine_used'], f15='C'),
        _f('amount_of_deductible', Tier.OPTIONAL, 'float', synonyms=['num_amount_of_deductible'], f15='A, C'),
        _f('amount_of_copayment', Tier.OPTIONAL, 'float', synonyms=['num_amount_of_copayment'], f15='C'),
        _f('date_of_payment', Tier.OPTIONAL, 'date', synonyms=[], f15='C'),
        _f('payment_reference__number', Tier.OPTIONAL, 'str', synonyms=['txt_payment_reference_ number'], f15='C'),
        _f('date_claim_intimation', Tier.OPTIONAL, 'date', synonyms=[], f15='C'),
        _f('bonus_sum_insured', Tier.OPTIONAL, 'float', synonyms=['num_bonus_sum_insured'], f15='B,C'),
        _f('claim_reopened_or_not', Tier.OPTIONAL, 'bool', synonyms=['boo_claim_reopened_or_not'], f15='C'),
        _f('surgical_or_non_surgical_treatment', Tier.OPTIONAL, 'bool', synonyms=['boo_surgical_or_non_surgical_treatment'], f15='C'),
        _f('out_patient_or_in_patient_treatment', Tier.OPTIONAL, 'bool', synonyms=['boo_out-patient_or_in-patient_treatment'], f15='C'),
        _f('irda_product_id', Tier.OPTIONAL, 'str', synonyms=['txt_irda_product_id'], f15='A,B,C'),
        _f('critical_illness_disease_code', Tier.OPTIONAL, 'str', synonyms=['txt_critical_illness_disease_code'], f15='C'),
        _f('opening_claim_provision', Tier.OPTIONAL, 'float', synonyms=['num_opening_claim_provision'], f15='C'),
        _f('closing_claim_provision', Tier.OPTIONAL, 'float', synonyms=['num_closing_claim_provision'], f15='C'),
        _f('transaction_id', Tier.OPTIONAL, 'str', synonyms=['txt_transaction_id'], f15='A,B,C'),
        _f('date_transaction_id', Tier.OPTIONAL, 'date', synonyms=[], f15='A,B,C'),
        _f('reason_for__hospitalisation', Tier.OPTIONAL, 'int', synonyms=['txt_reason_for_ hospitalisation'], f15='C'),
        _f('treating_doctor__registration__number', Tier.OPTIONAL, 'str', synonyms=['txt_treating_doctor_ registration_ number'], f15='C'),
        _f('type_of_admission', Tier.OPTIONAL, 'int', synonyms=['txt_type_of_admission'], f15='C'),
        _f('room_category__occupied', Tier.OPTIONAL, 'int', synonyms=['txt_room_category_ occupied'], f15='C'),
        _f('date_of_receipt_of__complete_claim_document', Tier.OPTIONAL, 'date', synonyms=['date_of_receipt_of _complete_claim_document'], f15='C'),
        _f('patient_id', Tier.OPTIONAL, 'str', synonyms=['txt_patient_id'], f15='C'),
        _f('date_of_commencement_of_first_insurance_without_break', Tier.OPTIONAL, 'date', synonyms=[], f15='A,B,C'),
        _f('recoveries_towards_co_pay', Tier.OPTIONAL, 'float', synonyms=['recoveries_towards_co-pay'], f15='C'),
        _f('recoveries_towards_deductibles', Tier.OPTIONAL, 'float', synonyms=['recoveries_towards deductibles'], f15='C'),
        _f('recoveries_owing_to_sub_limits_imposed', Tier.OPTIONAL, 'float', synonyms=['recoveries_owing_to_sub_limits imposed'], f15='C'),
        _f('recoveries_towards_non_medical_items', Tier.OPTIONAL, 'float', synonyms=['recoveries_towards_non-medical items'], f15='C'),
        _f('recoveries_towards_proportionate_deductions', Tier.OPTIONAL, 'float', synonyms=[], f15='C'),
        _f('recoveries_over_above_si_cb_corporate_floater', Tier.OPTIONAL, 'float', synonyms=['recoveries_over_above_si_cb-corporate_floater'], f15='C'),
        _f('ground_of_fraud_rejection', Tier.OPTIONAL, 'str', synonyms=['ground of fraud rejection'], f15='C'),
        _f('fraud_commited_by', Tier.OPTIONAL, 'str', synonyms=['fraud commited by'], f15='C'),
        _f('name_of_supect_fraudester', Tier.OPTIONAL, 'str', synonyms=['name of supect/ fraudester'], f15='C'),
        _f('suspect_fraudster_id_proof_name', Tier.OPTIONAL, 'str', synonyms=['suspect/ fraudster id proof name'], f15='C'),
        _f('suspect_fraudster_id_proof_number', Tier.OPTIONAL, 'float', synonyms=['suspect/ fraudster id proof number'], f15='C'),
        _f('radiologist_name_1', Tier.OPTIONAL, 'str', synonyms=['radiologist_name 1'], f15='C'),
        _f('radiologist_address_1', Tier.OPTIONAL, 'float', synonyms=['radiologist address 1'], f15='C'),
        _f('radiologist_pin_code_1', Tier.OPTIONAL, 'int', synonyms=['radiologist pin code 1'], f15='C'),
        _f('radiologist_registration_number_1', Tier.OPTIONAL, 'float', synonyms=['radiologist registration number 1'], f15='C'),
        _f('radiologist_email_id_1', Tier.OPTIONAL, 'float', synonyms=['radiologist email id 1'], f15='C'),
        _f('radiologist_phone_number_1', Tier.OPTIONAL, 'int', synonyms=['radiologist phone number 1'], f15='C'),
        _f('radiologist_longitude_1', Tier.OPTIONAL, 'float', synonyms=['radiologist_longitude 1'], f15='C'),
        _f('radiologist_latitude_1', Tier.OPTIONAL, 'float', synonyms=['radiologist_latitude 1'], f15='C'),
        _f('radiologist_name_2', Tier.OPTIONAL, 'str', synonyms=['radiologist_name 2'], f15='C'),
        _f('radiologist_address_2', Tier.OPTIONAL, 'float', synonyms=['radiologist address 2'], f15='C'),
        _f('radiologist_pin_code_2', Tier.OPTIONAL, 'int', synonyms=['radiologist pin code 2'], f15='C'),
        _f('radiologist_registration_number_2', Tier.OPTIONAL, 'float', synonyms=['radiologist registration number 2'], f15='C'),
        _f('radiologist_email_id_2', Tier.OPTIONAL, 'float', synonyms=['radiologist email id 2'], f15='C'),
        _f('radiologist_phone_number_2', Tier.OPTIONAL, 'int', synonyms=['radiologist phone number 2'], f15='C'),
        _f('radiologist_longitude_2', Tier.OPTIONAL, 'float', synonyms=['radiologist_longitude 2'], f15='C'),
        _f('radiologist_latitude_2', Tier.OPTIONAL, 'float', synonyms=['radiologist_latitude 2'], f15='C'),
        _f('pathologist_name_1', Tier.OPTIONAL, 'str', synonyms=['pathologist_name 1'], f15='C'),
        _f('pathologist_address_1', Tier.OPTIONAL, 'float', synonyms=['pathologist address 1'], f15='C'),
        _f('pathologist_pin_code_1', Tier.OPTIONAL, 'int', synonyms=['pathologist pin code 1'], f15='C'),
        _f('pathologist_registration_number_1', Tier.OPTIONAL, 'float', synonyms=['pathologist registration number 1'], f15='C'),
        _f('pathologist_email_id_1', Tier.OPTIONAL, 'float', synonyms=['pathologist email id 1'], f15='C'),
        _f('pathologist_phone_number_1', Tier.OPTIONAL, 'int', synonyms=['pathologist phone number 1'], f15='C'),
        _f('pathologist_longitude_1', Tier.OPTIONAL, 'float', synonyms=['pathologist_longitude 1'], f15='C'),
        _f('pathologist_latitude_1', Tier.OPTIONAL, 'float', synonyms=['pathologist_latitude 1'], f15='C'),
        _f('pathologist_name_2', Tier.OPTIONAL, 'str', synonyms=['pathologist_name 2'], f15='C'),
        _f('pathologist_address_2', Tier.OPTIONAL, 'float', synonyms=['pathologist address 2'], f15='C'),
        _f('pathologist_pin_code_2', Tier.OPTIONAL, 'int', synonyms=['pathologist pin code 2'], f15='C'),
        _f('pathologist_registration_number_2', Tier.OPTIONAL, 'float', synonyms=['pathologist registration number 2'], f15='C'),
        _f('pathologist_email_id_2', Tier.OPTIONAL, 'float', synonyms=['pathologist email id 2'], f15='C'),
        _f('pathologist_phone_number_2', Tier.OPTIONAL, 'int', synonyms=['pathologist phone number 2'], f15='C'),
        _f('pathologist_longitude_2', Tier.OPTIONAL, 'float', synonyms=['pathologist_longitude 2'], f15='C'),
        _f('pathologist_latitude_2', Tier.OPTIONAL, 'float', synonyms=['pathologist_latitude 2'], f15='C'),
        _f('hospital_address', Tier.OPTIONAL, 'float', synonyms=[], f15='C'),
        _f('hospital_type', Tier.OPTIONAL, 'int', synonyms=[], f15='C'),
        _f('hospital_email_id', Tier.OPTIONAL, 'float', synonyms=[], f15='C'),
        _f('hospital_contact_details', Tier.OPTIONAL, 'int', synonyms=[], f15='C'),
        _f('hospital_latitude', Tier.OPTIONAL, 'float', synonyms=[], f15='C'),
        _f('hospital_longitude', Tier.OPTIONAL, 'float', synonyms=[], f15='C'),
        _f('hospital_propreiter_name', Tier.OPTIONAL, 'str', synonyms=[], f15='C'),
        _f('hospital_propreiter_contact_number', Tier.OPTIONAL, 'int', synonyms=[], f15='C'),
        _f('name_of_proposer_policy_holder', Tier.OPTIONAL, 'str', synonyms=['name_of_proposer / policy holder'], f15='C'),
        _f('proposer_policy_holder__detail_address', Tier.OPTIONAL, 'str', synonyms=['proposer / policy holder_ detail_address'], f15=None),
        _f('proposer_policy_holder_phone_number', Tier.OPTIONAL, 'int', synonyms=['proposer / policy holder_phone_number'], f15='C'),
        _f('proposer_policy_holder_pan_card_number', Tier.OPTIONAL, 'float', synonyms=['proposer / policy holder_pan_card_number'], f15='C'),
        _f('adhaar_number_of_policyholder', Tier.OPTIONAL, 'int', synonyms=['txt_adhaar_number_of_policyholder'], f15='A'),
        _f('claimaint_name', Tier.OPTIONAL, 'str', synonyms=[], f15='C'),
        _f('claimaint_gender', Tier.OPTIONAL, 'str', synonyms=['claimaint gender'], f15='C'),
        _f('claimaint_date_of_birth', Tier.OPTIONAL, 'date', synonyms=['claimaint_date of birth'], f15='C'),
        _f('claimaint_address', Tier.OPTIONAL, 'str', synonyms=[], f15='C'),
        _f('claimaint_pin_code', Tier.OPTIONAL, 'int', synonyms=[], f15='C'),
        _f('claimaint_phone_number', Tier.OPTIONAL, 'int', synonyms=[], f15='C'),
        _f('claimaint_pan_card_number', Tier.OPTIONAL, 'str', synonyms=[], f15='C'),
        _f('treating_doctor_name', Tier.OPTIONAL, 'str', synonyms=[], f15='C'),
        _f('treating_doctor_pan_card', Tier.OPTIONAL, 'str', synonyms=[], f15='C'),
        _f('investigation_agency_name', Tier.OPTIONAL, 'str', synonyms=[], f15='C'),
        _f('investigaton_propriete__name', Tier.OPTIONAL, 'str', synonyms=['investigaton_propriete_ name'], f15='C'),
        _f('investigator_pan_card', Tier.OPTIONAL, 'str', synonyms=[], f15='C'),
        _f('intermediary_code', Tier.OPTIONAL, 'str', synonyms=[], f15='C'),
        _f('intermediary_license_number', Tier.OPTIONAL, 'str', synonyms=[], f15='C'),
        _f('intermediary_name', Tier.OPTIONAL, 'str', synonyms=[], f15='C'),
        _f('investigator_gstn_number', Tier.OPTIONAL, 'str', synonyms=[], f15='C'),
        _f('srf_id_on_covid_report', Tier.OPTIONAL, 'str', synonyms=['srf id_on_covid_report'], f15='C'),
        _f('icmr_id_on_covid_report', Tier.OPTIONAL, 'str', synonyms=['icmr id_on_covid_report'], f15='C'),
        _f('preauth_date', Tier.OPTIONAL, 'date', synonyms=['preauth date'], f15='C'),
        _f('pre_authorised_amount', Tier.OPTIONAL, 'float', synonyms=['pre -authorised amount'], f15='C'),
        _f('authorization_date', Tier.OPTIONAL, 'date', synonyms=['authorization date'], f15='C'),
        _f('final_authorization_amount', Tier.OPTIONAL, 'date', synonyms=['final authorization amount'], f15='C'),
        _f('expected_date_of_admission', Tier.OPTIONAL, 'date', synonyms=['expected date of admission'], f15='C'),
        _f('expected_date_of_discharge', Tier.OPTIONAL, 'date', synonyms=['expected date of discharge'], f15='C'),
        _f('cashless_denial_date', Tier.OPTIONAL, 'date', synonyms=[], f15='C'),
        _f('cashless_denial_reason', Tier.OPTIONAL, 'str', synonyms=[], f15='C'),
        _f('financial_year', Tier.OPTIONAL, 'str', synonyms=[], f15=None),
        _f('cashless_paid', Tier.OPTIONAL, 'float', synonyms=['num_cashless_paid'], f15='C'),
    ],

    # ---- MEMBER_MASTER (55 fields: 13 DB-schema + 42 F15-only) ----
    "member_master": [
        # -- DB-schema fields (canonical = ORM column name) --
        _f('tpa_code', Tier.IMPORTANT, 'int', synonyms=['txt_tpa_code', 'tpa name'], f15='A,B,C'),
        _f('insurer_code', Tier.IMPORTANT, 'int', synonyms=['txt_insurer_code', 'insurer name'], f15='A,B,C'),
        _f('master_policy_number', Tier.IMPORTANT, 'str', synonyms=['txt_master_policy_number'], f15='A,B,C'),
        _f('policy_number', Tier.CRITICAL, 'str', synonyms=['txt_policy_number'], f15='A,B,C'),
        _f('member_reference_key', Tier.CRITICAL, 'str', synonyms=['txt_member_reference_key', 'member id', 'mrk', 'member ref'], f15='B,C'),
        _f('employee_id', Tier.IMPORTANT, 'str', synonyms=['emp id', 'employee id'], f15='B,C'),
        _f('date_of_birth', Tier.IMPORTANT, 'date', synonyms=['dob', 'date of birth'], f15='B,C'),
        _f('age', Tier.IMPORTANT, 'int', synonyms=['num_age_of_insured', 'age_of_insured'], f15='B,C'),
        _f('coverage_start', Tier.OPTIONAL, 'date', synonyms=['date_policy_start', 'coverage start', 'cover start', 'enrolment date'], f15='A,B,C'),
        _f('coverage_end', Tier.OPTIONAL, 'date', synonyms=['date_policy_end', 'coverage end', 'cover end'], f15='A,B,C'),
        _f('gender', Tier.IMPORTANT, 'int', synonyms=['txt_gender'], f15='B,C'),
        _f('sum_insured', Tier.CRITICAL, 'float', synonyms=['num_sum_insured', 'sum insured', 'si'], f15='B,C'),
        _f('relationship', Tier.IMPORTANT, 'int', synonyms=['txt_relationship_of_insured', 'relationship_of_insured', 'relation'], f15='B'),
        # -- F15-only fields (informational; not stored in current DB schema) --
        _f('product_type', Tier.OPTIONAL, 'int', synonyms=['txt_product_type'], f15='A,B,C'),
        _f('type_of_policy', Tier.OPTIONAL, 'int', synonyms=['txt_type_of_policy'], f15='A,B,C'),
        _f('pre_existing_diseases_covered', Tier.OPTIONAL, 'bool', synonyms=['boo_pre-existing_diseases_covered'], f15='B'),
        _f('waiver_of_1st_year__exclusion', Tier.OPTIONAL, 'bool', synonyms=['boo_waiver_of_1st_year_ exclusion'], f15='B'),
        _f('maternity_cover', Tier.OPTIONAL, 'bool', synonyms=['boo_maternity_cover'], f15='B'),
        _f('baby_cover_as_part_of_maternity', Tier.OPTIONAL, 'bool', synonyms=['boo_baby_cover_as_part_of_maternity'], f15='B'),
        _f('floater_applicable', Tier.OPTIONAL, 'bool', synonyms=['boo_floater_applicable'], f15='B,C'),
        _f('occupation', Tier.OPTIONAL, 'int', synonyms=['txt_occupation'], f15='B'),
        _f('post_hospitalization_beyond__60_days_is_covered', Tier.OPTIONAL, 'bool', synonyms=['boo_post_hospitalization_beyond_ 60_days_is_covered'], f15='B'),
        _f('out_patient_cover', Tier.OPTIONAL, 'bool', synonyms=['boo_out_patient_cover'], f15='B'),
        _f('baby_cover_from_date_of_birth', Tier.OPTIONAL, 'bool', synonyms=['boo_baby_cover_from_date_of_birth'], f15='B'),
        _f('ambulance_cover', Tier.OPTIONAL, 'bool', synonyms=['boo_ambulance_cover'], f15='B'),
        _f('health_check_up', Tier.OPTIONAL, 'bool', synonyms=['boo_health_check_up'], f15='B'),
        _f('pre_existing_diseases__declared', Tier.OPTIONAL, 'bool', synonyms=['boo_pre_existing_diseases_ declared'], f15='B'),
        _f('details_of_pre_existing__diseases_level_i', Tier.OPTIONAL, 'int', synonyms=['txt_details_of_pre_existing_ diseases_level_i'], f15='B'),
        _f('endorsement', Tier.OPTIONAL, 'bool', synonyms=['boo_endorsement'], f15='A,B'),
        _f('endorsement_type', Tier.OPTIONAL, 'str', synonyms=['txt_endorsement_type'], f15='A'),
        _f('endorsement_number', Tier.OPTIONAL, 'str', synonyms=['txt_endorsement_number'], f15='A,B'),
        _f('details_of_pre_existing_diseases_level_ii', Tier.OPTIONAL, 'int', synonyms=['txt_details_of_pre_existing_diseases_level_ii'], f15='B'),
        _f('details_of_pre_existing_diseases_level_iii', Tier.OPTIONAL, 'int', synonyms=['txt_details_of_pre_existing_diseases_level_iii'], f15='B'),
        _f('pre_existing_diseases__covered_with_a_waiting_period', Tier.OPTIONAL, 'bool', synonyms=['boo_pre_existing_diseases_ covered_with_a_waiting_period'], f15='B'),
        _f('waiting_period_for_ped', Tier.OPTIONAL, 'int', synonyms=['num_waiting_period for ped'], f15='B'),
        _f('maternity_cover_given__with_a__waiting_period', Tier.OPTIONAL, 'bool', synonyms=['boo_maternity_cover_given_ with_a_ waiting_period'], f15='B'),
        _f('pre_hospitalization_beyond_30_days_is_covered', Tier.OPTIONAL, 'bool', synonyms=['boo_pre_hospitalization_beyond_30_days_is_covered'], f15='B'),
        _f('urban_metro_rural__village', Tier.OPTIONAL, 'int', synonyms=['txt_urban_metro_rural_ village'], f15='B'),
        _f('date_member_entry', Tier.OPTIONAL, 'date', synonyms=[], f15='B'),
        _f('date_member_exit', Tier.OPTIONAL, 'date', synonyms=[], f15='B'),
        _f('bonus_sum_insured', Tier.OPTIONAL, 'float', synonyms=['num_bonus_sum_insured'], f15='B,C'),
        _f('irda_product_id', Tier.OPTIONAL, 'str', synonyms=['txt_irda_product_id'], f15='A,B,C'),
        _f('previous_policy_number', Tier.OPTIONAL, 'str', synonyms=['txt_previous_policy_number'], f15='A,B'),
        _f('previous_member_reference_key', Tier.OPTIONAL, 'str', synonyms=['txt_previous_member_reference_key'], f15='B'),
        _f('transaction_id', Tier.OPTIONAL, 'str', synonyms=['txt_transaction_id'], f15='A,B,C'),
        _f('date_transaction_id', Tier.OPTIONAL, 'date', synonyms=[], f15='A,B,C'),
        _f('whether_sub_standard__cases', Tier.OPTIONAL, 'bool', synonyms=['boo_whether_sub_standard _cases'], f15='B'),
        _f('sub_standard_cases', Tier.OPTIONAL, 'str', synonyms=['txt_sub_standard_cases'], f15='B'),
        _f('if__ped_code_is_99__description', Tier.OPTIONAL, 'str', synonyms=['txt_if _ped_code_is_99_ description'], f15='B'),
        _f('endorsement_effective_date', Tier.OPTIONAL, 'date', synonyms=[], f15='A,B'),
        _f('date_of_commencement_of_first_insurance_without_break', Tier.OPTIONAL, 'date', synonyms=[], f15='A,B,C'),
        _f('number_of_years_complete', Tier.OPTIONAL, 'int', synonyms=[], f15='B'),
        _f('type_of_premium', Tier.OPTIONAL, 'bool', synonyms=['boo_type_of_premium'], f15='A,B'),
        _f('financial_year', Tier.OPTIONAL, 'str', synonyms=[], f15=None),
        _f('distribution_channel_code', Tier.OPTIONAL, 'str', synonyms=['txt_distribution_channel_code'], f15=None),
    ],

    # ---- POLICY_MASTER (40 fields: 10 DB-schema + 30 F15-only) ----
    "policy_master": [
        # -- DB-schema fields (canonical = ORM column name) --
        _f('tpa_code', Tier.IMPORTANT, 'int', synonyms=['txt_tpa_code', 'tpa name'], f15='A,B,C'),
        _f('insurer_code', Tier.IMPORTANT, 'int', synonyms=['txt_insurer_code', 'insurer name'], f15='A,B,C'),
        _f('master_policy_number', Tier.IMPORTANT, 'str', synonyms=['txt_master_policy_number'], f15='A,B,C'),
        _f('policy_number', Tier.CRITICAL, 'str', synonyms=['txt_policy_number', 'policy no', 'policy no.'], f15='A,B,C'),
        _f('policy_start_date', Tier.CRITICAL, 'date', synonyms=['date_policy_start', 'policy start date', 'start date'], f15='A,B,C'),
        _f('policy_end_date', Tier.CRITICAL, 'date', synonyms=['date_policy_end', 'policy end date', 'end date'], f15='A,B,C'),
        _f('product_type', Tier.IMPORTANT, 'int', synonyms=['txt_product_type'], f15='A,B,C'),
        _f('policy_type', Tier.IMPORTANT, 'int', synonyms=['txt_type_of_policy', 'type_of_policy'], f15='A,B,C'),
        _f('corporate_floater_sum_insured', Tier.OPTIONAL, 'float', synonyms=['num_corporate_floater_sum_insured', 'corporate buffer'], f15='A'),
        _f('policy_premium', Tier.CRITICAL, 'float', synonyms=['num_policy_premium', 'total premium', 'premium'], f15='A'),
        # -- F15-only fields (informational; not stored in current DB schema) --
        _f('uw_office_code', Tier.OPTIONAL, 'str', synonyms=['txt_uw_office_code'], f15='A'),
        _f('primary_members_insured', Tier.OPTIONAL, 'int', synonyms=['num_primary_members_insured'], f15='A'),
        _f('no_of_members_insured', Tier.OPTIONAL, 'int', synonyms=['no.of members insured'], f15='A'),
        _f('hospitalisation_is_with_or_without_pa', Tier.OPTIONAL, 'bool', synonyms=['boo_hospitalisation_is_with_or_without_pa'], f15='A'),
        _f('type_of_hospital_in_which__treatment_is_permitted', Tier.OPTIONAL, 'int', synonyms=['txt_type_of_hospital_in_which_ treatment_is_permitted'], f15='A'),
        _f('pan_or_tan_of_policyholder', Tier.OPTIONAL, 'str', synonyms=['txt_pan_or_tan_of_policyholder'], f15='A'),
        _f('adhaar_number_of_policyholder', Tier.OPTIONAL, 'int', synonyms=['txt_adhaar_number_of_policyholder'], f15='A'),
        _f('pin_code_of_policyholder', Tier.OPTIONAL, 'int', synonyms=['txt_pin_code_of_policyholder'], f15='A'),
        _f('city_of_policyholder', Tier.OPTIONAL, 'str', synonyms=['txt_city_of_policyholder'], f15='A'),
        _f('district_of_policyholder', Tier.OPTIONAL, 'int', synonyms=['txt_district_of_policyholder'], f15='A'),
        _f('state_of_policyholder', Tier.OPTIONAL, 'int', synonyms=['txt_state_of_policyholder'], f15='A'),
        _f('type_of_premium', Tier.OPTIONAL, 'bool', synonyms=['boo_type_of_premium'], f15='A'),
        _f('policy_having_coinsurance', Tier.OPTIONAL, 'str', synonyms=['txt_policy_having_coinsurance'], f15='A'),
        _f('your_coinsurance_share', Tier.OPTIONAL, 'float', synonyms=['num_your_coinsurance_share'], f15='A'),
        _f('endorsement', Tier.OPTIONAL, 'bool', synonyms=['boo_endorsement'], f15='A,B'),
        _f('endorsement_number', Tier.OPTIONAL, 'str', synonyms=['txt_endorsement_number'], f15='A,B'),
        _f('endorsement_type', Tier.OPTIONAL, 'str', synonyms=['txt_endorsement_type'], f15='A'),
        _f('amount_of_deductible', Tier.OPTIONAL, 'float', synonyms=['num_amount_of_deductible'], f15='A, C'),
        _f('distribution_channel_code', Tier.OPTIONAL, 'int', synonyms=['txt_distribution_channel_code'], f15='A'),
        _f('irda_product_id', Tier.OPTIONAL, 'str', synonyms=['txt_irda_product_id'], f15='A,B,C'),
        _f('previous_policy_number', Tier.OPTIONAL, 'str', synonyms=['txt_previous_policy_number'], f15='A,B'),
        _f('transaction_id', Tier.OPTIONAL, 'str', synonyms=['txt_transaction_id'], f15='A,B,C'),
        _f('date_transaction_id', Tier.OPTIONAL, 'date', synonyms=[], f15='A,B,C'),
        _f('endorsement_effective_date', Tier.OPTIONAL, 'date', synonyms=[], f15='A,B'),
        _f('date_of_commencement_of_first_insurance_without_break', Tier.OPTIONAL, 'date', synonyms=[], f15='A,B,C'),
        _f('financial_year', Tier.OPTIONAL, 'str', synonyms=[], f15=None),
        _f('date_of_birth', Tier.OPTIONAL, 'str', synonyms=[], f15=None),
        _f('age_of_insured', Tier.OPTIONAL, 'str', synonyms=['num_age_of_insured'], f15=None),
        _f('gender', Tier.OPTIONAL, 'str', synonyms=['txt_gender'], f15=None),
        _f('sum_insured', Tier.OPTIONAL, 'str', synonyms=['num_sum_insured'], f15=None),
    ],

    # ---- CLIENT MASTER and TERMS (no F15 equivalent) ----
    "client_master": [
        _f("client_id", Tier.CRITICAL, "id", synonyms=["client id"]),
        _f("client_name", Tier.CRITICAL, "str", synonyms=["client name", "name of the client", "insured name"]),
        _f("primary_industry", Tier.OPTIONAL, "str", synonyms=["primary industry", "industry"]),
        _f("total_employee_count", Tier.OPTIONAL, "int", synonyms=["total employees"]),
    ],
    "terms": [
        _f("policy_number", Tier.CRITICAL, "str", synonyms=["policy number", "txt_policy_number"]),
        _f("policy_year", Tier.OPTIONAL, "int", synonyms=["policy year", "policy period", "year"]),
        _f("term_type", Tier.CRITICAL, "str", synonyms=["term", "term type", "benefit", "clause", "benefit type"]),
        _f("value", Tier.IMPORTANT, "float", synonyms=["term value", "limit", "amount", "percent", "pct"]),
        _f("unit", Tier.OPTIONAL, "str", synonyms=["unit", "uom"]),
        _f("text_value", Tier.OPTIONAL, "str", synonyms=["text", "clause text", "description", "wording"]),
        _f("applies_to", Tier.OPTIONAL, "str", synonyms=["applies to", "scope"]),
    ],
}


# Governed value normalization
CLAIM_STATUS_MASTER = {
    "1": "Settled Fully", "2": "Settled Partially",
    "3": "Repudiated", "4": "Outstanding",
}
RELATIONSHIP_MASTER = {
    "1": "Self", "2": "Spouse", "3": "Father", "4": "Mother",
    "5": "Son", "6": "Daughter", "99": "Others",
}
GENDER_MASTER = {"1": "Male", "2": "Female", "3": "Other"}


def mandatory_fields(table: str):
    return [f["canonical"] for f in REGISTRY[table] if f["mandatory"]]


def critical_fields(table: str):
    return [f["canonical"] for f in REGISTRY[table] if f["tier"] == Tier.CRITICAL]


def all_synonyms(table: str):
    m = {}
    for f in REGISTRY[table]:
        for s in [f["canonical"]] + f["synonyms"]:
            m[s.lower()] = f["canonical"]
    return m
