"""sprint3 multi-year policyversion + manual mapping

Revision ID: 39290a9fd2a7
Revises: 790f13125204
Create Date: 2026-07-15 13:04:08.582364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39290a9fd2a7'
down_revision: Union[str, Sequence[str], None] = '790f13125204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mapping_audit',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('upload_batch_id', sa.String(length=36), nullable=True),
    sa.Column('mapping_profile_id', sa.String(length=36), nullable=True),
    sa.Column('mapping_profile_version', sa.Integer(), nullable=True),
    sa.Column('raw_column', sa.String(length=255), nullable=False),
    sa.Column('selected_canonical', sa.String(length=128), nullable=True),
    sa.Column('previous_suggestion', sa.String(length=128), nullable=True),
    sa.Column('confidence_before', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mapping_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mapping_audit_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('member_coverage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('member_reference_key', sa.String(length=50), nullable=False),
    sa.Column('policy_number', sa.String(length=100), nullable=False),
    sa.Column('family_id', sa.String(length=40), nullable=True),
    sa.Column('sum_insured', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('coverage_start', sa.Date(), nullable=True),
    sa.Column('coverage_end', sa.Date(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('dataset_version_id', sa.String(length=36), nullable=False),
    sa.Column('upload_batch_id', sa.String(length=36), nullable=False),
    sa.Column('raw_file_id', sa.String(length=36), nullable=False),
    sa.Column('raw_row_index', sa.Integer(), nullable=False),
    sa.Column('data_quality_caveat', sa.Boolean(), nullable=False),
    sa.Column('restricted', sa.Boolean(), nullable=False),
    sa.Column('policy_version_id', sa.String(length=36), nullable=True),
    sa.Column('policy_year', sa.Integer(), nullable=True),
    sa.Column('linkage_status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('member_coverage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_member_coverage_dataset_version_id'), ['dataset_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_coverage_member_reference_key'), ['member_reference_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_coverage_policy_number'), ['policy_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_coverage_policy_version_id'), ['policy_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_coverage_policy_year'), ['policy_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_coverage_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('policy_version',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('policy_number', sa.String(length=100), nullable=False),
    sa.Column('policy_year', sa.Integer(), nullable=True),
    sa.Column('policy_start_date', sa.Date(), nullable=True),
    sa.Column('policy_end_date', sa.Date(), nullable=True),
    sa.Column('renewal_cycle', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('insurer_code', sa.String(length=20), nullable=True),
    sa.Column('tpa_code', sa.String(length=20), nullable=True),
    sa.Column('premium', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('sum_insured_structure', sa.JSON(), nullable=True),
    sa.Column('source_dataset_version_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('dataset_version_id', sa.String(length=36), nullable=False),
    sa.Column('upload_batch_id', sa.String(length=36), nullable=False),
    sa.Column('raw_file_id', sa.String(length=36), nullable=False),
    sa.Column('raw_row_index', sa.Integer(), nullable=False),
    sa.Column('data_quality_caveat', sa.Boolean(), nullable=False),
    sa.Column('restricted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_version_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_version_dataset_version_id'), ['dataset_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_version_policy_number'), ['policy_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_version_policy_year'), ['policy_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_version_source_dataset_version_id'), ['source_dataset_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_version_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.add_column(sa.Column('policy_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('member_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('provider_code', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('outstanding_amount', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('incurred_amount', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('claim_type', sa.String(length=24), nullable=True))
        batch_op.add_column(sa.Column('bill_breakup_available', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('policy_version_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('policy_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('linkage_status', sa.String(length=16), nullable=False))
        batch_op.alter_column('sum_insured',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
        batch_op.alter_column('total_amount_claimed',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
        batch_op.alter_column('total_claim_paid',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_claim_policy_version_id'), ['policy_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_policy_year'), ['policy_year'], unique=False)

    with op.batch_alter_table('claim_bill_component', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deduction_amount', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('policy_version_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('policy_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('linkage_status', sa.String(length=16), nullable=False))
        batch_op.alter_column('amount_claimed',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_claim_bill_component_policy_version_id'), ['policy_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_bill_component_policy_year'), ['policy_year'], unique=False)

    with op.batch_alter_table('mapping_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('ignored_columns', sa.JSON(), nullable=True))

    with op.batch_alter_table('member_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_id', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('coverage_start', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('coverage_end', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('policy_version_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('policy_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('linkage_status', sa.String(length=16), nullable=False))
        batch_op.alter_column('sum_insured',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_member_master_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_master_policy_version_id'), ['policy_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_master_policy_year'), ['policy_year'], unique=False)

    with op.batch_alter_table('policy_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('policy_version_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('policy_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('linkage_status', sa.String(length=16), nullable=False))
        batch_op.alter_column('policy_premium',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
        batch_op.alter_column('corporate_floater_sum_insured',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_policy_master_policy_version_id'), ['policy_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_master_policy_year'), ['policy_year'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policy_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_master_policy_year'))
        batch_op.drop_index(batch_op.f('ix_policy_master_policy_version_id'))
        batch_op.alter_column('corporate_floater_sum_insured',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=16, scale=2),
               existing_nullable=True)
        batch_op.alter_column('policy_premium',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=16, scale=2),
               existing_nullable=True)
        batch_op.drop_column('linkage_status')
        batch_op.drop_column('policy_year')
        batch_op.drop_column('policy_version_id')

    with op.batch_alter_table('member_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_master_policy_year'))
        batch_op.drop_index(batch_op.f('ix_member_master_policy_version_id'))
        batch_op.drop_index(batch_op.f('ix_member_master_family_id'))
        batch_op.alter_column('sum_insured',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=16, scale=2),
               existing_nullable=True)
        batch_op.drop_column('linkage_status')
        batch_op.drop_column('policy_year')
        batch_op.drop_column('policy_version_id')
        batch_op.drop_column('coverage_end')
        batch_op.drop_column('coverage_start')
        batch_op.drop_column('family_id')

    with op.batch_alter_table('mapping_profile', schema=None) as batch_op:
        batch_op.drop_column('ignored_columns')
        batch_op.drop_column('priority')
        batch_op.drop_column('version')

    with op.batch_alter_table('claim_bill_component', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claim_bill_component_policy_year'))
        batch_op.drop_index(batch_op.f('ix_claim_bill_component_policy_version_id'))
        batch_op.alter_column('amount_claimed',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=16, scale=2),
               existing_nullable=True)
        batch_op.drop_column('linkage_status')
        batch_op.drop_column('policy_year')
        batch_op.drop_column('policy_version_id')
        batch_op.drop_column('deduction_amount')

    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claim_policy_year'))
        batch_op.drop_index(batch_op.f('ix_claim_policy_version_id'))
        batch_op.alter_column('total_claim_paid',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=16, scale=2),
               existing_nullable=True)
        batch_op.alter_column('total_amount_claimed',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=16, scale=2),
               existing_nullable=True)
        batch_op.alter_column('sum_insured',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=16, scale=2),
               existing_nullable=True)
        batch_op.drop_column('linkage_status')
        batch_op.drop_column('policy_year')
        batch_op.drop_column('policy_version_id')
        batch_op.drop_column('bill_breakup_available')
        batch_op.drop_column('claim_type')
        batch_op.drop_column('incurred_amount')
        batch_op.drop_column('outstanding_amount')
        batch_op.drop_column('provider_code')
        batch_op.drop_column('member_id')
        batch_op.drop_column('policy_id')

    with op.batch_alter_table('policy_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_version_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_policy_version_source_dataset_version_id'))
        batch_op.drop_index(batch_op.f('ix_policy_version_policy_year'))
        batch_op.drop_index(batch_op.f('ix_policy_version_policy_number'))
        batch_op.drop_index(batch_op.f('ix_policy_version_dataset_version_id'))
        batch_op.drop_index(batch_op.f('ix_policy_version_client_id'))

    op.drop_table('policy_version')
    with op.batch_alter_table('member_coverage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_coverage_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_member_coverage_policy_year'))
        batch_op.drop_index(batch_op.f('ix_member_coverage_policy_version_id'))
        batch_op.drop_index(batch_op.f('ix_member_coverage_policy_number'))
        batch_op.drop_index(batch_op.f('ix_member_coverage_member_reference_key'))
        batch_op.drop_index(batch_op.f('ix_member_coverage_dataset_version_id'))

    op.drop_table('member_coverage')
    with op.batch_alter_table('mapping_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mapping_audit_tenant_id'))

    op.drop_table('mapping_audit')
    # ### end Alembic commands ###
