"""sprint5 simulation_config

Revision ID: 6bd674c17e67
Revises: 95abd8f9858e
Create Date: 2026-07-15 14:46:58.407981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bd674c17e67'
down_revision: Union[str, Sequence[str], None] = '95abd8f9858e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_config',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('room_rent_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('copay_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('parent_copay_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('disease_cap', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('maternity_sublimit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulation_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulation_config_tenant_id'), ['tenant_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulation_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulation_config_tenant_id'))

    op.drop_table('simulation_config')
    # ### end Alembic commands ###
