"""sprint2 baseline schema

Revision ID: 790f13125204
Revises:
Create Date: 2026-07-14 21:11:42.591652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '790f13125204'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('claim',
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('policy_number', sa.String(length=100), nullable=False),
    sa.Column('claim_number', sa.String(length=30), nullable=False),
    sa.Column('member_reference_key', sa.String(length=50), nullable=True),
    sa.Column('diagnosis_code_l1', sa.String(length=20), nullable=True),
    sa.Column('hospital_name', sa.String(length=120), nullable=True),
    sa.Column('date_of_admission', sa.Date(), nullable=True),
    sa.Column('date_of_discharge', sa.Date(), nullable=True),
    sa.Column('sum_insured', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('total_amount_claimed', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('total_claim_paid', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('claim_status', sa.String(length=24), nullable=True),
    sa.Column('hospital_is_network', sa.Boolean(), nullable=True),
    sa.Column('copay_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('dataset_version_id', sa.String(length=36), nullable=False),
    sa.Column('upload_batch_id', sa.String(length=36), nullable=False),
    sa.Column('raw_file_id', sa.String(length=36), nullable=False),
    sa.Column('raw_row_index', sa.Integer(), nullable=False),
    sa.Column('data_quality_caveat', sa.Boolean(), nullable=False),
    sa.Column('restricted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('claim_id')
    )
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claim_claim_number'), ['claim_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_dataset_version_id'), ['dataset_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_policy_number'), ['policy_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('claim_bill_component',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('claim_number', sa.String(length=30), nullable=False),
    sa.Column('component', sa.String(length=48), nullable=False),
    sa.Column('amount_claimed', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('room_rent_linked', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('dataset_version_id', sa.String(length=36), nullable=False),
    sa.Column('upload_batch_id', sa.String(length=36), nullable=False),
    sa.Column('raw_file_id', sa.String(length=36), nullable=False),
    sa.Column('raw_row_index', sa.Integer(), nullable=False),
    sa.Column('data_quality_caveat', sa.Boolean(), nullable=False),
    sa.Column('restricted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claim_bill_component', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claim_bill_component_claim_number'), ['claim_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_bill_component_dataset_version_id'), ['dataset_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_bill_component_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('client_master',
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('primary_industry', sa.String(length=150), nullable=True),
    sa.Column('total_employee_count', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('dataset_version_id', sa.String(length=36), nullable=False),
    sa.Column('upload_batch_id', sa.String(length=36), nullable=False),
    sa.Column('raw_file_id', sa.String(length=36), nullable=False),
    sa.Column('raw_row_index', sa.Integer(), nullable=False),
    sa.Column('data_quality_caveat', sa.Boolean(), nullable=False),
    sa.Column('restricted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('client_id')
    )
    with op.batch_alter_table('client_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_master_dataset_version_id'), ['dataset_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_master_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('mapping_profile',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('file_kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('signature', sa.String(length=32), nullable=False),
    sa.Column('field_map', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('times_reused', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mapping_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mapping_profile_signature'), ['signature'], unique=False)
        batch_op.create_index(batch_op.f('ix_mapping_profile_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('member_master',
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('policy_number', sa.String(length=100), nullable=False),
    sa.Column('member_reference_key', sa.String(length=50), nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('sum_insured', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('relationship', sa.String(length=30), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('dataset_version_id', sa.String(length=36), nullable=False),
    sa.Column('upload_batch_id', sa.String(length=36), nullable=False),
    sa.Column('raw_file_id', sa.String(length=36), nullable=False),
    sa.Column('raw_row_index', sa.Integer(), nullable=False),
    sa.Column('data_quality_caveat', sa.Boolean(), nullable=False),
    sa.Column('restricted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('member_id')
    )
    with op.batch_alter_table('member_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_member_master_dataset_version_id'), ['dataset_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_master_member_reference_key'), ['member_reference_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_master_policy_number'), ['policy_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_master_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('policy_master',
    sa.Column('policy_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('policy_number', sa.String(length=100), nullable=False),
    sa.Column('master_policy_number', sa.String(length=100), nullable=True),
    sa.Column('insurer_code', sa.String(length=20), nullable=True),
    sa.Column('tpa_code', sa.String(length=20), nullable=True),
    sa.Column('product_type', sa.String(length=10), nullable=True),
    sa.Column('policy_type', sa.String(length=10), nullable=True),
    sa.Column('policy_start_date', sa.Date(), nullable=True),
    sa.Column('policy_end_date', sa.Date(), nullable=True),
    sa.Column('policy_premium', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('corporate_floater_sum_insured', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('dataset_version_id', sa.String(length=36), nullable=False),
    sa.Column('upload_batch_id', sa.String(length=36), nullable=False),
    sa.Column('raw_file_id', sa.String(length=36), nullable=False),
    sa.Column('raw_row_index', sa.Integer(), nullable=False),
    sa.Column('data_quality_caveat', sa.Boolean(), nullable=False),
    sa.Column('restricted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('policy_id')
    )
    with op.batch_alter_table('policy_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_master_dataset_version_id'), ['dataset_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_master_policy_number'), ['policy_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_master_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('raw_file',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('file_kind', sa.String(length=32), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=128), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('immutable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_file', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_file_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_file_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('upload_batch',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('raw_file_id', sa.String(length=36), nullable=False),
    sa.Column('file_kind', sa.String(length=32), nullable=False),
    sa.Column('field_map', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['raw_file_id'], ['raw_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('upload_batch', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upload_batch_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('correction_overlay',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('upload_batch_id', sa.String(length=36), nullable=False),
    sa.Column('raw_row_index', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=128), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('corrected_value', sa.Text(), nullable=True),
    sa.Column('corrected_by', sa.String(length=128), nullable=False),
    sa.Column('corrected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['upload_batch_id'], ['upload_batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('correction_overlay', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_correction_overlay_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('dataset_version',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('upload_batch_id', sa.String(length=36), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('dq_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('dq_result_id', sa.String(length=36), nullable=True),
    sa.Column('readiness_status', sa.String(length=48), nullable=True),
    sa.Column('restricted', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(length=128), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('activated_by', sa.String(length=128), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['upload_batch_id'], ['upload_batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dataset_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_version_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('dq_result',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('upload_batch_id', sa.String(length=36), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('readiness', sa.String(length=32), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['upload_batch_id'], ['upload_batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dq_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dq_result_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('review_item',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('upload_batch_id', sa.String(length=36), nullable=False),
    sa.Column('raw_row_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('proposed_action', sa.Text(), nullable=True),
    sa.Column('issues', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['upload_batch_id'], ['upload_batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_item_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('validation_issue',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('upload_batch_id', sa.String(length=36), nullable=False),
    sa.Column('raw_row_index', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('field', sa.String(length=128), nullable=True),
    sa.Column('rule', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('quarantined', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['upload_batch_id'], ['upload_batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('validation_issue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_issue_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('override_record',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('dataset_version_id', sa.String(length=36), nullable=False),
    sa.Column('upload_batch_id', sa.String(length=36), nullable=False),
    sa.Column('admin_user', sa.String(length=128), nullable=False),
    sa.Column('dq_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('failed_components', sa.JSON(), nullable=False),
    sa.Column('impacted_modules', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('resulting_status', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('override_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_override_record_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('override_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_override_record_tenant_id'))

    op.drop_table('override_record')
    with op.batch_alter_table('validation_issue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_issue_tenant_id'))

    op.drop_table('validation_issue')
    with op.batch_alter_table('review_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_item_tenant_id'))

    op.drop_table('review_item')
    with op.batch_alter_table('dq_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dq_result_tenant_id'))

    op.drop_table('dq_result')
    with op.batch_alter_table('dataset_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_version_tenant_id'))

    op.drop_table('dataset_version')
    with op.batch_alter_table('correction_overlay', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_correction_overlay_tenant_id'))

    op.drop_table('correction_overlay')
    with op.batch_alter_table('upload_batch', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_batch_tenant_id'))

    op.drop_table('upload_batch')
    with op.batch_alter_table('raw_file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_file_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_raw_file_sha256'))

    op.drop_table('raw_file')
    with op.batch_alter_table('policy_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_master_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_policy_master_policy_number'))
        batch_op.drop_index(batch_op.f('ix_policy_master_dataset_version_id'))

    op.drop_table('policy_master')
    with op.batch_alter_table('member_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_master_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_member_master_policy_number'))
        batch_op.drop_index(batch_op.f('ix_member_master_member_reference_key'))
        batch_op.drop_index(batch_op.f('ix_member_master_dataset_version_id'))

    op.drop_table('member_master')
    with op.batch_alter_table('mapping_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mapping_profile_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_mapping_profile_signature'))

    op.drop_table('mapping_profile')
    with op.batch_alter_table('client_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_master_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_client_master_dataset_version_id'))

    op.drop_table('client_master')
    with op.batch_alter_table('claim_bill_component', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claim_bill_component_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_claim_bill_component_dataset_version_id'))
        batch_op.drop_index(batch_op.f('ix_claim_bill_component_claim_number'))

    op.drop_table('claim_bill_component')
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claim_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_claim_policy_number'))
        batch_op.drop_index(batch_op.f('ix_claim_dataset_version_id'))
        batch_op.drop_index(batch_op.f('ix_claim_claim_number'))

    op.drop_table('claim')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_tenant_id'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
