"""sprint4 metric_config

Revision ID: 95abd8f9858e
Revises: 39290a9fd2a7
Create Date: 2026-07-15 13:51:51.504328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95abd8f9858e'
down_revision: Union[str, Sequence[str], None] = '39290a9fd2a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_config',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('large_claim_threshold', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metric_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metric_config_tenant_id'), ['tenant_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metric_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_config_tenant_id'))

    op.drop_table('metric_config')
    # ### end Alembic commands ###
