"""sprint6 benefit_term + terms_audit

Revision ID: bf5b4e9e2a15
Revises: 6bd674c17e67
Create Date: 2026-07-15 17:46:45.292631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf5b4e9e2a15'
down_revision: Union[str, Sequence[str], None] = '6bd674c17e67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benefit_term',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('policy_number', sa.String(length=100), nullable=True),
    sa.Column('term_type', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.Column('applies_to', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_snippet', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('confirmed_by', sa.String(length=128), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('dataset_version_id', sa.String(length=36), nullable=False),
    sa.Column('upload_batch_id', sa.String(length=36), nullable=False),
    sa.Column('raw_file_id', sa.String(length=36), nullable=False),
    sa.Column('raw_row_index', sa.Integer(), nullable=False),
    sa.Column('data_quality_caveat', sa.Boolean(), nullable=False),
    sa.Column('restricted', sa.Boolean(), nullable=False),
    sa.Column('policy_version_id', sa.String(length=36), nullable=True),
    sa.Column('policy_year', sa.Integer(), nullable=True),
    sa.Column('linkage_status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('benefit_term', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_benefit_term_dataset_version_id'), ['dataset_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_benefit_term_policy_number'), ['policy_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_benefit_term_policy_version_id'), ['policy_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_benefit_term_policy_year'), ['policy_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_benefit_term_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_benefit_term_term_type'), ['term_type'], unique=False)

    op.create_table('terms_audit',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('benefit_term_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('before_status', sa.String(length=16), nullable=True),
    sa.Column('after_status', sa.String(length=16), nullable=False),
    sa.Column('before_value', sa.String(length=64), nullable=True),
    sa.Column('after_value', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('terms_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_terms_audit_benefit_term_id'), ['benefit_term_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_terms_audit_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terms_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_terms_audit_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_terms_audit_benefit_term_id'))

    op.drop_table('terms_audit')
    with op.batch_alter_table('benefit_term', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_benefit_term_term_type'))
        batch_op.drop_index(batch_op.f('ix_benefit_term_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_benefit_term_policy_year'))
        batch_op.drop_index(batch_op.f('ix_benefit_term_policy_version_id'))
        batch_op.drop_index(batch_op.f('ix_benefit_term_policy_number'))
        batch_op.drop_index(batch_op.f('ix_benefit_term_dataset_version_id'))

    op.drop_table('benefit_term')
    # ### end Alembic commands ###
